import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import "react-responsive-carousel/lib/styles/carousel.min.css";
import styles from "@/styles/Home.module.css";
import Header from "@/components/header";
import Breadcrumb from "@/components/navigation/breadcrumbs";
import EquipmentDetail from "./equipment-detail";

const inter = Inter({ subsets: ["latin"] });

const Body = () => {
    return (
        <div className="xl:px-[155px] md:px-5">
            <Breadcrumb />
            <EquipmentDetail />
        </div>
    );
};

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <Body />
        </>
    );
}
